/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function TestModel({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/BHmQZajwSh3oASrM/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#4b4d52']} />
      <group {...props} dispose={null}>
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.7}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={1}
          shadow-camera-far={2500}
          shadow-camera-left={-1250}
          shadow-camera-right={1250}
          shadow-camera-top={1250}
          shadow-camera-bottom={-1250}
          position={[97, 197, 287]}
        />
        <mesh
          name="Rectangle"
          geometry={nodes.Rectangle.geometry}
          material={materials['Rectangle Material']}
          castShadow
          receiveShadow
          position={[28.1, 166.88, -16.95]}
        />
        <OrthographicCamera
          name="Personal Camera"
          makeDefault={true}
          far={100000}
          near={-100000}
          position={[201.42, 140.38, 969.39]}
          rotation={[-0.14, 0.2, 0.03]}
        />
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" position={[0, 1, 0]} />
      </group>
    </>
  )
}